<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EventSpotter</title>
    <link rel="stylesheet" href="{{url('assets/style/style.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{url('assets//images/logo.png')}}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/382f336cbc.js"></script>
</head>

<body style="background:#e1e1e1;">
    <div class="header">
        <div class="row align-items-center">
            <div class="col-md-12 text-center">
                <div class="headerlogo">
                    <a href="index.html"><img class="img-fluid" src="/assets/images/headerLogo.png" alt=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mb-5" style="border:1px solid rgb(111, 176, 192);">
        <h5 class="mt-5 policy">Cookie Policy</h5>
        <p>Updated at 2021-11-22
        </p>
        <h5 class="policy">Definitions and key terms</h5>
        <p>To help explain things as clearly as possible in this Cookie Policy, every time any of these terms are referenced, are strictly defined as:</p>
        <ul style="padding-left:20px;">
            <li><strong>Cookie :</strong> Small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.</li>
            <li class="mt-2"><strong>Website :</strong> When this policy mentions “Company,” “we,” “us,” or “our,” it refers to Event Spotter, that is responsible for your information under this Cookie Policy.
            </li>
            <li class="mt-2"><strong>Device :</strong> Any internet connected device such as a phone, tablet, computer or any other device that can be used to visit Event Spotter and use the services.
            </li>
            <li class="mt-2"><strong>Personal Data :</strong> Any information that directly, indirectly, or in connection with other information including a personal identification number allows for the identification or identifiability of a natural person.
            </li>
            <li class="mt-2"><strong>Service :</strong> Refers to the service provided by Event Spotter as described in the relative terms (if available) and on this platform.
            </li>
            <li class="mt-2"><strong>Third-party service :</strong> Refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.
            </li>
            <li class="mt-2"><strong>Website</strong> Event Spotter’s" site, which can be accessed via this URL:
                <a href=" https://theeventspotter.com"> https://theeventspotter.com</a>
            </li>
            <li class="mt-2"><strong>YOU</strong> a person or entity that is registered with Event Spotter to use the Services.

            </li>
        </ul>
        <h5 class="mt-1 policy">Introduction</h5>
        <p> This Cookie Policy explains how Event Spotter and its affiliates (collectively "Event Spotter", "we", "us", and "ours"), use cookies and similar technologies to recognize you when you visit our website, including without limitation
            <a href="https://theeventspotter.com">https://theeventspotter.com</a> and any related URLs, mobile or localized versions and related domains / sub-domains ("Websites"). It explains what these technologies are and why we use them, as well as
            the choices for how to control them.</p>


        <h5 class="mt-1 policy">What is a cookie?</h5>
        <p> A cookie is a small text file that is stored on your computer or other internet connected device in order to identify your browser, provide analytics, remember information about you such as your language preference or login information. They're
            completely safe and can't be used to run programs or deliver viruses to your device.</p>


        <h5 class="policy">Why do we use cookies?
        </h5>
        <p>We use first party and/or third-party cookies on our website for various purposes such as:</p>
        <ul style="padding-left:20px;">
            <li>To facilitate the operation and functionality of our website.</li>
            <li>To improve your experience of our website and make navigating around them quicker and easier.
            </li>
            <li> To allow us to make a bespoke user experience for you and for us to understand what is useful or of interest to you.
            </li>
            <li>To analyze how our website is used and how best we can customize it.</li>
            <li>To identify future prospects and personalize marketing and sales interactions with it.
            </li>
            <li>To facilitate the tailoring of online advertising to your interests.</li>
        </ul>

        <h5 class="mt-1 policy">What type of cookies does Event Spotter use?
        </h5>
        <p>Cookies can either be session cookies or persistent cookies. A session cookie expires automatically when you close your browser. A persistent cookie will remain until it expires or you delete your cookies. Expiration dates are set in the cookies
            themselves; some may expire after a few minutes while others may expire after multiple years. Cookies placed by the website you’re visiting are called “first party cookies”. <br> Strictly Necessary cookies are necessary for our website to
            function and cannot be switched off in our systems. They are essential in order to enable you to navigate around the website and use its features. If you remove or disable these cookies, we cannot guarantee that you will be able to use our
            website.
        </p>

        <h5 class="policy">We use the following types of cookies in our website:
        </h5>

        <ul style="padding-left:20px;">
            <li>Errors and Omissions Disclaimer.
            </li>
            <li>Event Spotter is not responsible for any content, code or any other imprecision.
            </li>
            <li>Event Spotter does not provide warranties or guarantees.
            </li>
            <li>In no event shall Event Spotter be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the
                use of the Service or the contents of the Service. Event Spotter reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior notice.
            </li>
        </ul>

        <h5 class="mt-1 policy">General Disclaimer
        </h5>
        <p>The Event Spotter Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Event Spotter is a distributor and not a publisher of the content supplied by third
            parties; as such, Event Spotter exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible
            via the Event Spotter Service. Without limiting the foregoing, Event Spotter specifically disclaims all warranties and representations in any content transmitted on or in connection with the Event Spotter Service or on sites that may appear
            as links on the Event Spotter Service, or in the products provided as a part of, or otherwise in connection with, the Event Spotter Service, including without limitation any warranties of merchantability, fitness for a particular purpose or
            non-infringement of third-party rights. No oral advice or written information given by Event Spotter or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is
            subject to change without notice. Without limiting the foregoing, Event Spotter does not warrant that the Event Spotter Service will be uninterrupted, uncorrupted, timely, or error-free.
        </p>
        <h5 class="mt-1 policy">Advertising Cookies
        </h5>
        <p>These cookies collect information over time about your online activity on the website and other online services to make online advertisements more relevant and effective to you. This is known as interest-based advertising. They also perform functions
            like preventing the same ad from continuously reappearing and ensuring that ads are properly displayed for advertisers. Without cookies, it’s really hard for an advertiser to reach its audience, or to know how many ads were shown and how many
            clicks they received.</p>
        <h5 class="mt-1 policy">How you can manage cookies?
        </h5>
        <p>Most browsers allow you to control cookies through their 'settings' preferences. However, if you limit the ability of websites to set cookies, you may worsen your overall user experience, since it will no longer be personalized to you. It may
            also stop you from saving customized settings like login information. Browser manufacturers provide help pages relating to cookie management in their products.</p>
        <ul style="margin-left: 30px;">
            <li>Google Chrome</li>
            <li>Internet Explorer</li>
            <li> Mozilla Firefox
            </li>
            <li> Safari (Desktop)</li>
            <li> Safari (Mobile)</li>
            <li> Android Browser</li>
            <li> Opera Mobile</li>
            <li> Opera </li>

        </ul>
        <p>Blocking and disabling cookies and similar technologies Wherever you're located you may also set your browser to block cookies and similar technologies, but this action may block our essential cookies and prevent our website from functioning properly,
            and you may not be able to fully utilize all of its features and services. You should also be aware that you may also lose some saved information (e.g. saved login details, site preferences) if you block cookies on your browser. Different
            browsers make different controls available to you. Disabling a cookie or category of cookie does not delete the cookie from your browser, you will need to do this yourself from within your browser, you should visit your browser's help menu
            for more information.
        </p>
        <h5 class="mt-1 policy">Changes To Our Cookie Policy</h5>
        <p> We may change our Service and policies, and we may need to make changes to this Cookie Policy so that they accurately reflect our Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before
            we make changes to this Cookie Policy and give you an opportunity to review them before they go into effect. Then, if you continue to use the Service, you will be bound by the updated Cookie Policy. If you do not want to agree to this or any
            updated Cookie Policy, you can delete your account.</p>
        <h5 class="mt-1 policy"> Your Consent
        </h5>
        <p>By using our website, registering an account, or making a purchase, you hereby consent to our Cookie Policy and agree to its terms.</p>
        <h5 class="mt-1 policy">Contact Us</h5>
        <p> Don't hesitate to contact us if you have any questions regarding our Cookie Policy. <br> Via Email:
            <a type="mail" href="contact@theeventspotter.com">contact@theeventspotter.com</a></p>
    </div>
    <script src="https://use.fontawesome.com/382f336cbc.js"></script>
</body>

</html>