<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EventSpotter</title>
    <link rel="stylesheet" href="{{url('assets/style/style.css')}}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{{url('assets//images/logo.png')}}" type="image/x-icon">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://use.fontawesome.com/382f336cbc.js"></script>
</head>

<body style="background:#e1e1e1;">
    <div class="header">
        <div class="row align-items-center">
            <div class="col-md-12 text-center">
                <div class="headerlogo">
                    <a href="index.html"><img class="img-fluid" src="/assets/images/headerLogo.png" alt=""></a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mb-5" style="border:1px solid rgb(111, 176, 192);">
        <h5 class="mt-5 policy">Disclaimer Policy</h5>
        <p>Updated at 2021-11-22
        </p>
        <p>Event Spotter hereby grants you access to https://theeventspotter.com (“the Website”) and invites you to purchase the services offered here.
        </p>
        <h5 class="policy">Definitions and key terms</h5>
        <p>To help explain things as clearly as possible in this Disclaimer, every time any of these terms are referenced, are strictly defined as:
        </p>
        <p><strong>Cookie: </strong>small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
        </p>
        <p><strong>Cookie: </strong>when this policy mentions “Company,” “we,” “us,” or “our,” it refers to Event Spotter, (10125 Campus way south Upper Marlboro, 20774. Maryland. United States.) that is responsible for your information under this Disclaimer.
        </p>
        <p><strong>Service: </strong>refers to the service provided by Event Spotter as described in the relative terms (if available) and on this platform.
        </p>
        <p><strong>Website: </strong>Event Spotter’s" site, which can be accessed via this URL:
            <a href="https://theeventspotter.com">https://theeventspotter.com</a>
        </p>
        <p><strong>You:</strong>a person or entity that is registered with Event Spotter to use the Services.
        </p>
        <h5 class="mt-4 policy">Limited liability</h5>
        <p>Event Spotter endeavors to update and/or supplement the content of the website on a regular basis. Despite our care and attention, content may be incomplete and/or incorrect.</p>
        <p>The materials offered on the website are offered without any form of guarantee or claim to their correctness. These materials can be changed at any time without prior notice from Event Spotter. Particularly, all prices on the website are stated
            subject to typing and programming errors. No liability is assumed for the implications of such errors. No agreement is concluded on the basis of such errors.</p>
        <p>Event Spotter shall not bear any liability for hyperlinks to websites or services of third parties included on the website. From our website, you can visit other websites by following hyperlinks to such external sites. While we strive to provide
            only quality links to useful and ethical websites, we have no control over the content and nature of these sites. These links to other websites do not imply a recommendation for all the content found on these sites. Site owners and content
            may change without notice and may occur before we have the opportunity to remove a link which may have gone ‘bad’.
        </p>
        <p>Please be also aware that when you leave our website, other sites may have different privacy policies and terms which are beyond our control. Please be sure to check the Privacy Policies of these sites as well as their "Terms of Service" before
            engaging in any business or uploading any information.
        </p>
        <h5 class="mt-4 policy">Errors and Omissions Disclaimer</h5>
        <p>Event Spotter is not responsible for any content, code or any other imprecision.
        </p>
        <p>Event Spotter does not provide warranties or guarantees. In no event shall Event Spotter be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence
            or other tort, arising out of or in connection with the use of the Service or the contents of the Service. Event Spotter reserves the right to make additions, deletions, or modifications to the contents on the Service at any time without prior
            notice.
        </p>
        <h5 class="mt-4 policy">General Disclaimer
        </h5>
        <p>The Event Spotter Service and its contents are provided "as is" and "as available" without any warranty or representations of any kind, whether express or implied. Event Spotter is a distributor and not a publisher of the content supplied by third
            parties; as such, Event Spotter exercises no editorial control over such content and makes no warranty or representation as to the accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible
            via the Event Spotter Service. Without limiting the foregoing, Event Spotter specifically disclaims all warranties and representations in any content transmitted on or in connection with the Event Spotter Service or on sites that may appear
            as links on the Event Spotter Service, or in the products provided as a part of, or otherwise in connection with, the Event Spotter Service, including without limitation any warranties of merchantability, fitness for a particular purpose or
            non-infringement of third-party rights. No oral advice or written information given by Event Spotter or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty. Price and availability information is
            subject to change without notice. Without limiting the foregoing, Event Spotter does not warrant that the Event Spotter Service will be uninterrupted, uncorrupted, timely, or error-free.
        </p>
        <h5 class="mt-4 policy">Advertising Disclosure
        </h5>
        <p>This website may contain third party advertisements and links to third party sites. Event Spotter does not make any representation as to the accuracy or suitability of any of the information contained in those advertisements or sites and does
            not accept any responsibility or liability for the conduct or content of those advertisements and sites and the offerings made by the third parties.</p>
        <p>Advertising keeps Event Spotter and many of the websites and services you use free of charge. We work hard to make sure that ads are safe, unobtrusive, and as relevant as possible. Third party advertisements and links to other sites where goods
            or services are advertised are not endorsements or recommendations by Event Spotter of the third-party sites, goods or services. Event Spotter takes no responsibility for the content of any of the ads, promises made, or the quality/reliability
            of the products or services offered in all advertisements.
        </p>
        <h5 class="mt-4 policy">Testimonials Disclosure</h5>
        <p>Any testimonials provided on this platform are opinions of those providing them. The information provided in the testimonials is not to be relied upon to predict results in your specific situation. The results you experience will be dependent
            on many factors including but not limited to your level of personal responsibility, commitment, and abilities, in addition to those factors that you and/or Event Spotter may not be able to anticipate.
        </p>
        <p>We will give honest testimonials to our visitors regardless of any discount. Any product or service that we test are individual experiences, reflecting real life experiences. The testimonials could be displayed on audio, text or video and are
            not necessarily representative of all of those who will use our products and/or services. Event Spotter does not guarantee the same results as the testimonials given on our platform. Testimonials presented on Event Spotter are applicable to
            the individuals writing them, and may not be indicative of future success of any other individuals. Please don’t hesitate to contact us if you would like to know more about testimonials, discounts, or any of the products/services that we review.</p>
        <h5 class="mt-4 policy">Your Consent</h5>
        <p>We've updated our Disclaimer to provide you with complete transparency into what is being set when you visit our site and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Disclaimer
            and agree to its terms.</p>
        <h5 class="mt-4 policy">Changes To Our Disclaimer</h5>
        <p>Should we update, amend or make any changes to this document so that they accurately reflect our Service and policies. Unless otherwise required by law, those changes will be prominently posted here. Then, if you continue to use the Service, you
            will be bound by the updated Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete your account.
        </p>
        <h5 class="mt-4 policy">Contact Us</h5>
        <p>Don't hesitate to contact us if you have any questions regarding this Disclaimer. <br> Via Email: <a href="contact@theeventspotter.com"> contact@theeventspotter.com</a>
        </p>


    </div>
    <script src="https://use.fontawesome.com/382f336cbc.js"></script>
</body>

</html> 